# Generated by Django 3.2.6 on 2021-08-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_creater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creater',
            new_name='creator',
        ),
    ]
